version: 2

models:
  - name: int_jaffle_data__customer_order_history
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null
      - name: total_orders
        data_tests:
          - not_null
      - name: total_spent
        data_tests:
          - not_null
      - name: avg_order_value
        data_tests:
          - not_null
      - name: first_order_date
        data_tests:
          - not_null
      - name: last_order_date
        data_tests:
          - not_null
      - name: customer_lifetime_days
        data_tests:
          - not_null
      - name: customer_segment
        data_tests:
          - not_null
          - accepted_values:
              values: ['VIP', 'Regular', 'New']

  - name: int_jaffle_data__order_items
    columns:
      - name: order_id
        data_tests:
          - not_null
      - name: customer_id
        data_tests:
          - not_null
      - name: ordered_at
        data_tests:
          - not_null
      - name: store_id
      - name: sku
        data_tests:
          - not_null
      - name: product_name
        tdata_tests:
          - not_null
      - name: product_type
      - name: product_price
        data_tests:
          - not_null
      - name: customer_order_seq
        data_tests:
          - not_null
      - name: previous_product_type