source:
  type: dbt
  serviceName: dataxdemo
  sourceConfig:
    config:
      type: DBT
      dbtConfigSource:
        dbtConfigType: local
        dbtCatalogFilePath: https://raw.githubusercontent.com/getcoraline/dataxdemo_github/58a29ba45bba5a5a2ed2927854fdec09b3e2c7e3/target/catalog.json
        dbtManifestFilePath: https://raw.githubusercontent.com/getcoraline/dataxdemo_github/58a29ba45bba5a5a2ed2927854fdec09b3e2c7e3/target/manifest.json
        dbtRunResultsFilePath: https://raw.githubusercontent.com/getcoraline/dataxdemo_github/58a29ba45bba5a5a2ed2927854fdec09b3e2c7e3/target/run_results.json
      dbtUpdateDescriptions: true
      includeTags: true
      dbtClassificationName: dbtTags

sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: "http://57.155.89.93:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: ${{ secrets.OPENMETADATA_JWT_TOKEN }}
    storeServiceConnection: true