source:
  type: dbt
  serviceName: dataxdemo
  sourceConfig:
    config:
      type: DBT
      dbtConfigSource:
        dbtConfigType: local
        dbtCatalogFilePath: ${{ github.workspace }}/target/catalog.json
        dbtManifestFilePath: ${{ github.workspace }}/target/manifest.json
        dbtRunResultsFilePath: ${{ github.workspace }}/target/run_results.json
      dbtUpdateDescriptions: true
      includeTags: true
      dbtClassificationName: dbtTags
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: "http://57.155.89.93:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: ${{ secrets.OPENMETADATA_JWT_TOKEN }}
    storeServiceConnection: true