source:
  type: dbt
  serviceName: uc-dataxdemo
  sourceConfig:
    config:
      type: DBT
      dbtConfigSource:
        dbtConfigType: local
        dbtCatalogFilePath: /home/vmadmin/openmetadata-docker/ingestion-volume-tmp/openmetadata/dbt_files/catalog.json
        dbtManifestFilePath: /home/vmadmin/openmetadata-docker/ingestion-volume-tmp/openmetadata/dbt_files/manifest.json
        dbtRunResultsFilePath: /home/vmadmin/openmetadata-docker/ingestion-volume-tmp/openmetadata/dbt_files/run_results.json
      dbtUpdateDescriptions: true
      includeTags: true
      dbtClassificationName: dbtTags

sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: "http://57.155.89.93:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: ${{ secrets.OPENMETADATA_JWT_TOKEN }}
    storeServiceConnection: true