version: 2

models:
  - name: stg_jaffle_data__customers
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: name

  - name: stg_jaffle_data__items
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: order_id
        data_tests:
          - not_null
      - name: sku
        data_tests:
          - not_null

  - name: stg_jaffle_data__orders
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: customer_id
        data_tests:
          - not_null
      - name: ordered_at
        data_tests:
          - not_null
      - name: store_id
      - name: subtotal
      - name: tax_paid
      - name: order_total

  - name: stg_jaffle_data__products
    columns:
      - name: sku
        data_tests:
          - unique
          - not_null
      - name: name
        data_tests:
          - not_null
      - name: type
      - name: price
        data_tests:
          - not_null
      - name: description