name: DBT CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-build-and-generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install dbt dbt-databricks
      
      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "
          dataxdemo:
            target: dev
            outputs:
              dev:
                type: databricks
                catalog: catalog_develop
                schema: default
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: /sql/1.0/warehouses/a1ed2d6ef2244b72
                token: ${{ secrets.DATABRICKS_TOKEN }}
                threads: 4
          " > ~/.dbt/profiles.yml
      
      - name: Run dbt debug
        run: dbt debug --profiles-dir ~/.dbt

      - name: Run dbt deps
        run: dbt deps --profiles-dir ~/.dbt

      - name: Run dbt build
        run: dbt build --profiles-dir ~/.dbt

      - name: Generate dbt docs
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: dbt docs generate --profiles-dir ~/.dbt