name: dbt Feature PR Checks

on:
  pull_request:
    branches:
      - feature/dev01

jobs:
  dbt-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (Set up Python 3.11 environment)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (Install dbt and dbt-databricks)
        run: pip install dbt dbt-databricks

      - name: Create profiles.yml (Configure dbt profile for development)
        run: |
          mkdir -p ~/.dbt
          echo "
          dataxdemo:
            target: dev
            outputs:
              dev:
                type: databricks
                catalog: catalog_develop
                schema: default
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: /sql/1.0/warehouses/a1ed2d6ef2244b72
                token: ${{ secrets.DATABRICKS_TOKEN }}
                threads: 4
          " > ~/.dbt/profiles.yml

      - name: Run dbt debug (Check connection and configuration)
        run: dbt debug --profiles-dir ~/.dbt

      - name: Run dbt deps (Install required dbt packages)
        run: dbt deps --profiles-dir ~/.dbt

      - name: Run unit tests and generic tests (Execute unit and generic tests)
        run: dbt test --profiles-dir ~/.dbt --select test_type:unit test_type:generic
