name: dbt QA Merge Checks

on:
  push:
    branches:
      - qa

jobs:
  dbt-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install dbt dbt-databricks

      - name: Create profiles.yml (Configure dbt profile for test environment)
        run: |
          mkdir -p ~/.dbt
          echo "
          dataxdemo:
            target: test
            outputs:
              test:
                type: databricks
                catalog: catalog_test
                schema: default
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
                token: ${{ secrets.DATABRICKS_TOKEN }}
                threads: 4
          " > ~/.dbt/profiles.yml

      - name: Run dbt debug (Check dbt connection and configuration)
        run: dbt debug --profiles-dir ~/.dbt

      - name: Run dbt deps (Install required dbt packages and dependencies)
        run: dbt deps --profiles-dir ~/.dbt

      - name: Run dbt run (Apply transformations to the data warehouse)
        run: dbt run --profiles-dir ~/.dbt

      - name: Run all tests (unit, generic, and singular tests)
        run: dbt test --profiles-dir ~/.dbt
