name: dbt QA Merge Checks

on:
  push:
    branches:
      - qa

jobs:
  dbt-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install dbt dbt-databricks

      - name: Create profiles.yml (Configure dbt profile for test environment)
        run: |
          mkdir -p ~/.dbt
          echo "
          dataxdemo:
            target: test
            outputs:
              test:
                type: databricks
                catalog: catalog_test
                schema: default
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
                token: ${{ secrets.DATABRICKS_TOKEN }}
                threads: 4
          " > ~/.dbt/profiles.yml

      - name: Run dbt debug (Check dbt connection and configuration)
        run: dbt debug --profiles-dir ~/.dbt

      - name: Run dbt deps (Install required dbt packages and dependencies)
        run: dbt deps --profiles-dir ~/.dbt

      - name: Run unit tests and generic tests
        id: unit_generic_tests
        run: dbt test --profiles-dir ~/.dbt --select test_type:unit test_type:generic
        continue-on-error: true

      - name: Notify Slack on unit and generic test failure
        if: steps.unit_generic_tests.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'dataxdemo-notifications'
          payload: |
            {
              "text": "Unit and generic dbt tests failed on qa branch",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Unit and generic dbt tests failed on qa branch*\n<${{ github.event.pull_request.html_url }}|Commit: ${{ github.event.pull_request.title }}>"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Pusher:*\n${{ github.event.pull_request.user.login }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Failed tests:*\nUnit and generic tests"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Run ID:*\n${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
      - name: Fail workflow if tests failed
        if: steps.unit_generic_tests.outcome == 'failure'
        run: exit 1

      - name: Run all tests (including singular tests)
        id: all_tests
        run: dbt test --profiles-dir ~/.dbt
        continue-on-error: true

      - name: Notify Slack on all tests failure
        if: steps.all_tests.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'dataxdemo-notifications'
          payload: |
            {
              "text": "All dbt tests (unit, generic, singular) failed on qa branch",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*All dbt tests (unit, generic, singular) failed on qa branch*\n<${{ github.event.pull_request.html_url }}|Commit: ${{ github.event.pull_request.title }}>"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Pusher:*\n${{ github.event.pull_request.user.login }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Failed tests:*\nAll tests (unit, generic, singular)"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Run ID:*\n${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Fail workflow if tests failed
        if: steps.all_tests.outcome == 'failure'
        run: exit 1

      - name: Run dbt run (Run data transformations on the catalog_test environment)
        run: dbt run --profiles-dir ~/.dbt