name: dbt Main Merge Actions

on:
  push:
    branches:
      - main

jobs:
  dbt-build-and-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install dbt-core dbt-databricks
          pip install openmetadata-ingestion

      - name: Create dbt profiles.yml (Configure dbt profile for production environment)
        run: |
          mkdir -p ~/.dbt
          echo "
          dataxdemo:
            target: prod
            outputs:
              prod:
                type: databricks
                catalog: catalog_main
                schema: default
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
                token: ${{ secrets.DATABRICKS_TOKEN }}
                threads: 4
          " > ~/.dbt/profiles.yml

      - name: Run dbt debug (Check dbt connection and configuration)
        run: dbt debug --profiles-dir ~/.dbt

      - name: Run dbt deps (Install required dbt packages and dependencies)
        run: dbt deps --profiles-dir ~/.dbt

      - name: Run dbt build (Build dbt models in the production environment)
        run: dbt build --profiles-dir ~/.dbt

      - name: Generate dbt docs (Create documentation for dbt models)
        run: dbt docs generate --profiles-dir ~/.dbt

      - name: Push to OpenMetadata (Ingest metadata into OpenMetadata)
        run: python -m metadata ingest -c path/to/openmetadata_config.yaml
