name: dbt feature/dev01 PR Checks

on:
  pull_request:
    branches:
      - qa

jobs:
  dbt-test-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Notify Slack on PR Creation
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'dataxdemo-notifications'
          payload: |
            {
              "text": "Notification: New pull request created on feature/dev01 branch",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Notification: New pull request created on feature/dev01 branch*\n<${{ github.event.pull_request.html_url }}|*View Details: ${{ github.event.pull_request.title }}*>"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Creator:*\n${{ github.event.pull_request.user.login }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install dbt dbt-databricks pytest pytest-cov

      - name: Create profiles.yml (Configure dbt profile for development environment)
        run: |
          mkdir -p ~/.dbt
          echo "
          dataxdemo:
            target: dev
            outputs:
              dev:
                type: databricks
                catalog: catalog_develop
                schema: default
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
                token: ${{ secrets.DATABRICKS_TOKEN }}
                threads: 4
          " > ~/.dbt/profiles.yml

      - name: Run dbt debug (Check dbt connection and configuration)
        run: dbt debug --profiles-dir ~/.dbt

      - name: Run dbt deps (Install required dbt packages and dependencies)
        run: dbt deps --profiles-dir ~/.dbt

      - name: Run Unit, Generic, and Great Expectations tests
        id: unit_generic_tests
        run: dbt test --profiles-dir ~/.dbt --select test_type:unit test_type:generic
        continue-on-error: true

      - name: Run Coverage Tests
        run: |
          pytest --cov=your_package_name tests/ > coverage.txt
          bash <(curl -s https://codecov.io/bash) -f coverage.txt
        continue-on-error: true

      - name: Notify Slack on test failures (Unit, Generic (with Great Expectations))
        if: steps.unit_generic_tests.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'dataxdemo-notifications'
          payload: |
            {
              "text": "Failure Notification: Tests failed on feature/dev01 branch",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Failure Notification: Tests failed on feature/dev01 branch*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|*Check Job Results*>"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Pusher:*\n${{ github.event.pull_request.user.login }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Failed tests:*\nUnit and Generic (with Great Expectations) tests"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Run ID:*\n${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Coverage Report to Slack
        run: |
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true

      - name: Notify Slack with Coverage Report Link
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'dataxdemo-notifications'
          payload: |
            {
              "text": "Coverage Report for feature/dev01 branch",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Coverage Report for feature/dev01 branch*\n<https://codecov.io/gh/${{ github.repository }}/pull/${{ github.event.number }}|*View Codecov Report*>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Fail workflow if tests failed
        if: steps.unit_generic_tests.outcome == 'failure'
        run: exit 1

      - name: Run dbt run (Run data transformations on the catalog_develop environment)
        run: dbt run --profiles-dir ~/.dbt
